### ISSUE TITLE
How to control vehicle gear?

### ISSUE THREAD

**Issue by wobuzhuchele** [BestMediaDeveloper/VsDotnet#1]
Hello,BestMedia Team. Thanks to your team for integrating Carsim.
When I use it, I find that the vehicle cannot be reversed when the variable "IMP_MODE_TRANS" is sent. How can I control the gear?

**Comment by BestMediaDeveloper** [comment]
Sorry for the delay in replying.

 IMP_MODE_TRANS is correct, but are you using VSVehicleVarDouble?

Variables starting with IMP should use VSVehicleVarImport.

in CarSimSample.cs

VarIMP_MODE_TRANS = new VSVehicleVarImport("IMP_MODE_TRANS", 0, CarSimMovement.VehicleSolver);
//Reverse -1 ,N =0
VarIMP_MODE_TRANS.Value = -1;

**Comment by wobuzhuchele** [comment]
thank you for your reply.
